# Generated by Django 5.0.6 on 2024-05-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtos_data_produtos_descricao_produtos_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='classe',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
