# Generated by Django 5.0.6 on 2024-06-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produtos_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='classe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
