# Generated by Django 5.0.6 on 2024-06-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
        ('produtos', '0003_produtos_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='titulo',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(null=True, to='produtos.produtos'),
        ),
    ]
