# Generated by Django 5.0.6 on 2024-06-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_remove_carrinho_cor_remove_carrinho_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='criado_em',
        ),
    ]
