# Generated by Django 5.0.6 on 2024-06-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0004_carrinho_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='produtos',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='usuario',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='cor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carrinho/'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='titulo',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
