# Generated by Django 5.0.6 on 2024-06-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0005_remove_carrinho_produtos_remove_carrinho_usuario_and_more'),
        ('produtos', '0004_alter_produtos_classe_alter_produtos_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='titulo',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos'),
        ),
    ]
