# Generated by Django 5.0.6 on 2024-06-02 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0006_remove_carrinho_cor_remove_carrinho_descricao_and_more'),
        ('produtos', '0004_alter_produtos_classe_alter_produtos_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.produtos'),
            preserve_default=False,
        ),
    ]
