# Generated by Django 5.0.6 on 2024-06-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0007_alter_carrinho_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='produto',
            new_name='produtocarrinho',
        ),
    ]
