# Generated by Django 5.0.6 on 2024-06-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0007_alter_carrinho_produto'),
        ('comprar_novamente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprar_novamente',
            name='data',
        ),
        migrations.RemoveField(
            model_name='comprar_novamente',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='comprar_novamente',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='comprar_novamente',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='comprar_novamente',
            name='titulo',
        ),
        migrations.AddField(
            model_name='comprar_novamente',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carrinho.carrinho'),
            preserve_default=False,
        ),
    ]
