# Generated by Django 5.0.6 on 2024-06-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprar_novamente', '0002_remove_comprar_novamente_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprar_novamente',
            old_name='produto',
            new_name='produtocomprarnovamente',
        ),
    ]
