# Generated by Django 5.0.6 on 2024-06-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempModel',
        ),
    ]
